---
swagger: '2.0'
info:
  description: ''
  version: '0.0.1'
  title: 'data'
  termsOfService: ''
  contact:
    name: ''
    email: 'steven.taylor@me.com'
  license:
    name: 'Steven Taylor'
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json

securityDefinitions:
  Oauth:
    type: oauth2
    scopes:
      open: no security
      user: a user
    flow: implicit
    authorizationUrl: https://my_aouth/

security:
- Oauth: []

paths:
  /health:
    x-swagger-router-controller: health
    get:
      tags:
      - health
      operationId: health
      security:
      - Oauth:
        - open
      responses:
        200:
          description: health information
          schema:
            $ref: '#/definitions/Status'
        default:
          $ref: '#/responses/Error'

  /bridge:
    x-swagger-router-controller: bridge
    get:
      tags:
      - bridge
      operationId: getBridge
      security:
      - Oauth:
        - user
      responses:
        200:
          description: bridge information
          schema:
            $ref: '#/definitions/BridgeInformation'
        default:
          $ref: '#/responses/Error'
    delete:
      tags:
      - bridge
      operationId: deleteBridge
      security:
      - Oauth:
        - user
      responses:
        200:
          description: ok
        default:
          $ref: '#/responses/Error'
    post:
      tags:
      - bridge
      operationId: createBridge
      security:
      - Oauth:
        - user
      parameters:
      - in: body
        name: data
        schema:
          $ref: '#/definitions/BridgeData'
      responses:
        200:
          description: bridge information
          schema:
            $ref: '#/definitions/BridgeInformation'
        default:
          $ref: '#/responses/Error'

  /swagger:
    x-swagger-pipe: swagger_raw

responses:

  Error:
    description: error
    schema:
      $ref: '#/definitions/Error'

definitions:

  Error:
    required:
    - code
    - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

  BridgeData:
    type: object
    required:
      - name
    additionalProperties: false
    properties:
      name:
        type: string

  BridgeInformation:
    type: object
    additionalProperties: false
    properties:
      serial:
        type: string
      pinCode:
        type: string
      setupURI:
        type: string

  Status:
    type: object
    additionalProperties: false
    properties:
      status:
        type: string
