apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-homekit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homekit
  template:
    metadata:
      labels:
        app: homekit
        context: sentinel
        version: v1
    spec:
      hostNetwork: true
      containers:
      -
        name: sentinel-homekit
        image: docker.io/hashneo/sentinel-homekit-x86_64:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "5000"
        - name : CONSUL
          value : "consul.home-sentinel.ai"
        - name: NEW_RELIC_NO_CONFIG_FILE
          value: "false"
        ports:
          -
            containerPort: 5000
            protocol: TCP

