apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-homekit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: homekit
        context: sentinel
        version: v1
    spec:
      hostNetwork: true
      containers:
        -
          name: sentinel-homekit
          image: docker.steventaylor.me/sentinel/homekit/homekit-x86_64
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "5000"
          - name: CONSUL
            value: "consul"
          ports:
            -
              containerPort: 5000
              protocol: TCP
          resources:
              limits:
                  memory: "512Mi"
              requests:
                  memory: "512Mi"
      imagePullSecrets:
      - name: regcred
      nodeSelector:
          beta.kubernetes.io/arch: amd64